printWidth: 140
useTabs: false
tabWidth: 4
preprocessorSymbolSets:
  - ""
  - "DEBUG"
  - "DEBUG_SOURCE_GENERATOR"
  - "SYSTEM_PRIVATE_CORELIB"
  - "NETSTANDARD2_0"
  - "ROSLYN4_4_OR_GREATER"
  - "ROSLYN4_7_OR_GREATER"
  - "NET6_0_OR_GREATER"
  - "NET7_0_OR_GREATER"
  - "NET8_0_OR_GREATER"
