branches:
  - name: stable
    channel: false
  - name: main
    channel: next
    prerelease: next
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/github'
    - assets:
      - path: 'artifacts/*.nupkg'
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo RELEASE_VERSION=\"${nextRelease.version}\" >> $GITHUB_ENV"
      prepareCmd: "RELEASE_NOTES=\"${nextRelease.notes}\" RELEASE_VERSION=\"${nextRelease.version}\" ./build/package.sh"
      publishCmd: "dotnet nuget push './artifacts/*.nupkg' --source $NUGET_SOURCE --api-key $NUGET_API_TOKEN"
