name: release-stable

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: test
    uses: ./.github/workflows/release.yml
    with:
      environment: stable
    secrets:
      NUGET_API_TOKEN: ${{ secrets.NUGET_API_TOKEN }}

  docs:
    uses: ./.github/workflows/docs.yml
    needs: release
    with:
      deploy: true
      environment: stable
      version: ${{ needs.release.outputs.version }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
